
liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    webp:
        generate: true

    filter_sets:
        cache: ~

        thumbnail_jpeg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [1600,900], mode: inset }
        thumbnail_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [1600,900], mode: inset }
        my_thumb_jpeg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [300, 200], mode: inset }
        my_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [300, 200], mode: inset }
                

