
liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    webp:
        generate: true

    filter_sets:
        cache: ~

       
        thumbnail:
            quality: 100
            filters:
                thumbnail: { size: [100, 200], mode: inset }
        
        my_thumb_jpeg:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [300, 200], mode: inset }
        my_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [300, 200], mode: inset }
                

